CRITICAL - 2025-01-17 13:23:18 --> Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2025-01-17 13:23:20 --> Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\topup\system\Helpers\number_helper.php:136
Stack trace:
#0 C:\xampp\htdocs\topup\system\Helpers\number_helper.php(55): format_number(6.0, 2, NULL, Array)
#1 C:\xampp\htdocs\topup\system\Debug\BaseExceptionHandler.php(145): number_to_size(6.0, 2)
#2 C:\xampp\htdocs\topup\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 C:\xampp\htdocs\topup\system\Debug\BaseExceptionHandler.php(241): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\topup\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 C:\xampp\htdocs\topup\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(Error), 500, 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\topup\system\Debug\Exceptions.php(148): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#8 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 C:\xampp\htdocs\topup\index.php(67): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-01-17 13:26:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 13:26:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 13:26:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 13:26:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 13:36:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 13:36:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 13:42:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 13:42:01 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:37:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:37:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:38:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:38:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:44:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:44:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:44:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:44:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:44:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:44:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:50:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:50:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:51:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:51:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 14:52:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 14:52:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:07:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:07:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:13:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:13:01 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:14:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:14:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:16:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:16:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:16:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:16:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:16:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:16:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:16:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:16:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:17:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:17:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-17 15:21:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'linkpaym_v8'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'linkpaym_v8', Object(SensitiveParameterValue), 'linkpaym_v8', 3306, '', 0)
#1 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#5 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#8 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#15 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\topup\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\topup\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\topup\system\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\topup\system\Session\Session.php(919): session_start()
#4 C:\xampp\htdocs\topup\system\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\topup\system\Config\Services.php(693): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
#7 C:\xampp\htdocs\topup\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\topup\system\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\topup\system\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\topup\system\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\topup\app\Controllers\View.php(24): session()
#12 C:\xampp\htdocs\topup\system\CodeIgniter.php(915): App\Controllers\View->__construct()
#13 C:\xampp\htdocs\topup\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\topup\system\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\topup\index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2025-01-17 15:21:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(98): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(919): session_start()
 4 SYSTEMPATH\Session\Session.php(241): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(693): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session(Object(Config\Session), false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(664): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::session()
10 SYSTEMPATH\Common.php(996): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 APPPATH\Controllers\View.php(24): session()
12 SYSTEMPATH\CodeIgniter.php(915): App\Controllers\View->__construct()
13 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->createController()
14 SYSTEMPATH\CodeIgniter.php(362): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
